<a href="https://colab.research.google.com/github/jenniferarzu/nyu-python-public-policy/blob/master/HW3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Jennifer Arzu**

# **HOMEWORK 3 Coding: Using keywords in the data to categorize 311 requests**

In [2]:
#importing pandas and mounting drive
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
df = pd.read_csv('/content/drive/My Drive/Data for Python/cleaned_311_data_hw3.csv', header='infer')

In [0]:
# Using pd.set_option() to make sure see all the rows in  dataframe
pd.set_option('display.max_columns', None) 
pd.set_option('display.max_rows', None)  
pd.set_option('display.max_colwidth', -1)

**Step 1. Create a function that checks each row in the 311 dataframe to see if the word "graffiti" is present in either the complaint_type value or descriptor value. Both columns may contain the word, so you should check both. If the word "graffiti" is found, the function should return the boolean value True. If "graffiti" is not found, the function should return the boolean value False.**
- Hint 1: The same way that we checked if the string "BRONX" existed in the community_board value in the cb_counts table during the lecture, you can check if "graffiti" exists in the descriptor or complaint_type values.
- Hint 2: The descriptor column contains some null/NaN values. You'll have trouble running a function on these. Before your function checks if "graffiti" is present in descriptor, the function should make sure that a descriptor value exists using pd.notnull(row.descriptor)
- Hint 3: Capitalization may be inconsistent. It could help to use .lower() to convert strings to lowercase.

In [5]:
#Using df.head() to quickly examine the column names
df.head()

,Unnamed: 0,Unnamed: 0.1,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,status,due_date,resolution_description,resolution_action_updated_date,community_board,bbl,borough,x_coordinate_(state_plane),y_coordinate_(state_plane),open_data_channel_type,park_facility_name,park_borough,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location
0,238,238,39887282,08/01/2018 01:42:01 AM,08/14/2018 02:42:12 PM,DPR,Department of Parks and Recreation,Maintenance or Facility,Structure - Outdoors,Park,10003.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NEW YORK,NaN,NaN,Closed,08/15/2018 01:42:01 AM,The Department of Parks and Recreation has completed the requested work order and corrected the problem.,08/14/2018 02:42:12 PM,0 Unspecified,NaN,Unspecified,NaN,NaN,PHONE,First Park,Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,353,353,39889407,08/01/2018 03:20:07 AM,08/23/2018 11:15:00 AM,DPR,Department of Parks and Recreation,Maintenance or Facility,Garbage or Litter,Park,11434.0,NaN,NaN,NaN,NaN,BAISLEY BOULEVARD,MERRICK BOULEVARD,INTERSECTION,JAMAICA,NaN,NaN,Closed,08/04/2018 03:20:07 AM,The Service Request submitted did not have sufficient location or complaint information for the agency to respond.,08/23/2018 11:15:00 AM,12 QUEENS,NaN,QUEENS,1048111.0,188479.0,PHONE,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.683778,-73.769744,"(40.68377771085733, -73.76974413109498)"
2,403,403,39893067,08/01/2018 04:19:15 AM,08/02/2018 08:19:55 AM,DPR,Department of Parks and Recreation,Maintenance or Facility,Hours of Operation,Park,11206.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BROOKLYN,NaN,NaN,Closed,08/04/2018 04:19:15 AM,The Department of Parks and Recreation has completed the requested work order and corrected the problem.,08/02/2018 08:19:55 AM,01 BROOKLYN,NaN,BROOKLYN,NaN,NaN,MOBILE,Ten Eyck Plaza,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,655,655,39890578,08/01/2018 07:32:33 AM,08/16/2018 10:28:38 AM,DPR,Department of Parks and Recreation,Maintenance or Facility,Garbage or Litter,Park,11691.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FAR ROCKAWAY,NaN,NaN,Closed,08/04/2018 07:32:33 AM,The Department of Parks and Recreation has completed the requested work order and corrected the problem.,08/16/2018 10:28:38 AM,14 QUEENS,NaN,QUEENS,NaN,NaN,PHONE,Westbourne Playground,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,658,658,39896325,08/01/2018 07:33:12 AM,09/04/2018 05:38:02 PM,DPR,Department of Parks and Recreation,Maintenance or Facility,Garbage or Litter,Park,11355.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FLUSHING,NaN,NaN,Closed,08/04/2018 07:33:12 AM,The condition was inspected and it was determined that no work order was necessary. The condition will not be inspected again for at least 90 days.,09/04/2018 05:38:02 PM,07 QUEENS,NaN,QUEENS,NaN,NaN,MOBILE,Maple Playground,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [0]:
#creating function with true values when graffiti present in complaint_type or descriptor column
#.lower used to lower-case responses in both columns ensuring that all graffiti responses are captured
def recode_graffiti_count(row):
  if pd.notnull(row.descriptor):
    if 'graffiti' in row.complaint_type.lower():
        return 'True'
    elif 'graffiti' in row.descriptor.lower():
        return 'True'
    else:
        return 'False'

**Step 2. Apply the function created in Step 1 to the 311 dataframe and create a new column called graffiti_flag that captures the output from the function.**

In [7]:
#applying function to 311 dataframe using df.apply
#viewing column header to check if the graffiti flag variable added
df['graffiti_flag'] = df.apply(recode_graffiti_count, axis=1)
df.head()

,Unnamed: 0,Unnamed: 0.1,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,status,due_date,resolution_description,resolution_action_updated_date,community_board,bbl,borough,x_coordinate_(state_plane),y_coordinate_(state_plane),open_data_channel_type,park_facility_name,park_borough,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location,graffiti_flag
0,238,238,39887282,08/01/2018 01:42:01 AM,08/14/2018 02:42:12 PM,DPR,Department of Parks and Recreation,Maintenance or Facility,Structure - Outdoors,Park,10003.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NEW YORK,NaN,NaN,Closed,08/15/2018 01:42:01 AM,The Department of Parks and Recreation has completed the requested work order and corrected the problem.,08/14/2018 02:42:12 PM,0 Unspecified,NaN,Unspecified,NaN,NaN,PHONE,First Park,Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1,353,353,39889407,08/01/2018 03:20:07 AM,08/23/2018 11:15:00 AM,DPR,Department of Parks and Recreation,Maintenance or Facility,Garbage or Litter,Park,11434.0,NaN,NaN,NaN,NaN,BAISLEY BOULEVARD,MERRICK BOULEVARD,INTERSECTION,JAMAICA,NaN,NaN,Closed,08/04/2018 03:20:07 AM,The Service Request submitted did not have sufficient location or complaint information for the agency to respond.,08/23/2018 11:15:00 AM,12 QUEENS,NaN,QUEENS,1048111.0,188479.0,PHONE,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.683778,-73.769744,"(40.68377771085733, -73.76974413109498)",False
2,403,403,39893067,08/01/2018 04:19:15 AM,08/02/2018 08:19:55 AM,DPR,Department of Parks and Recreation,Maintenance or Facility,Hours of Operation,Park,11206.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BROOKLYN,NaN,NaN,Closed,08/04/2018 04:19:15 AM,The Department of Parks and Recreation has completed the requested work order and corrected the problem.,08/02/2018 08:19:55 AM,01 BROOKLYN,NaN,BROOKLYN,NaN,NaN,MOBILE,Ten Eyck Plaza,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
3,655,655,39890578,08/01/2018 07:32:33 AM,08/16/2018 10:28:38 AM,DPR,Department of Parks and Recreation,Maintenance or Facility,Garbage or Litter,Park,11691.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FAR ROCKAWAY,NaN,NaN,Closed,08/04/2018 07:32:33 AM,The Department of Parks and Recreation has completed the requested work order and corrected the problem.,08/16/2018 10:28:38 AM,14 QUEENS,NaN,QUEENS,NaN,NaN,PHONE,Westbourne Playground,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4,658,658,39896325,08/01/2018 07:33:12 AM,09/04/2018 05:38:02 PM,DPR,Department of Parks and Recreation,Maintenance or Facility,Garbage or Litter,Park,11355.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FLUSHING,NaN,NaN,Closed,08/04/2018 07:33:12 AM,The condition was inspected and it was determined that no work order was necessary. The condition will not be inspected again for at least 90 days.,09/04/2018 05:38:02 PM,07 QUEENS,NaN,QUEENS,NaN,NaN,MOBILE,Maple Playground,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [8]:
#grouping by graffiti to view total counts of true vs false graffiti values

new_graffiti_flag = df.groupby('graffiti_flag').size().reset_index(name='count')
new_graffiti_flag

  graffiti_flag  count
0  False         38206
1  True          26371

**Step 3. Create another dataframe df_graffiti that only contains records where graffiti_flag is True. df_graffiti = df[df.grafitti_flag]**

In [0]:
#creating new dataframe with only true values of graffiti_flag
df_graffiti = df[df.graffiti_flag=='True']

In [10]:
df_graffiti.head()

,Unnamed: 0,Unnamed: 0.1,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,status,due_date,resolution_description,resolution_action_updated_date,community_board,bbl,borough,x_coordinate_(state_plane),y_coordinate_(state_plane),open_data_channel_type,park_facility_name,park_borough,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location,graffiti_flag
8,860,860,39897352,08/01/2018 08:21:08 AM,NaN,DSNY,Department of Sanitation,Graffiti,Graffiti,NaN,NaN,141 141 ST,141 ST,NaN,NaN,NaN,NaN,ADDRESS,NaN,NaN,NaN,Open,NaN,NaN,08/01/2018 08:21:08 AM,Unspecified QUEENS,NaN,QUEENS,NaN,NaN,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
9,876,876,39891938,08/01/2018 08:24:41 AM,08/30/2018 12:00:00 AM,DSNY,Department of Sanitation,Graffiti,Graffiti,Mixed Use,11237.0,237 IRVING AVENUE,IRVING AVENUE,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this property.,09/20/2018 03:18:01 PM,04 BROOKLYN,3.032900e+09,BROOKLYN,1007216.0,194542.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.700620,-73.917173,"(40.70061981717157, -73.91717344071574)",True
10,964,964,39897349,08/01/2018 08:40:34 AM,08/23/2018 12:00:00 AM,DSNY,Department of Sanitation,Graffiti,Graffiti,Residential,10467.0,345 EAST 205 STREET,EAST 205 STREET,NaN,NaN,NaN,NaN,ADDRESS,BRONX,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this property.,09/13/2018 04:19:12 PM,07 BRONX,2.033500e+09,BRONX,1018509.0,257554.0,UNKNOWN,Unspecified,BRONX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.873534,-73.876124,"(40.87353414980636, -73.87612406980227)",True
12,1007,1007,39893314,08/01/2018 08:47:45 AM,08/20/2018 12:00:00 AM,DSNY,Department of Sanitation,Graffiti,Graffiti,Mixed Use,11220.0,5506 5 AVENUE,5 AVENUE,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this property.,09/13/2018 04:19:12 PM,07 BROOKLYN,3.008310e+09,BROOKLYN,980544.0,173249.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.642204,-74.013354,"(40.64220432954161, -74.01335393443593)",True
13,1013,1013,39897422,08/01/2018 08:49:15 AM,08/28/2018 12:00:00 AM,DSNY,Department of Sanitation,Graffiti,Graffiti,Mixed Use,11237.0,884 HART STREET,HART STREET,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this property.,09/13/2018 04:19:12 PM,04 BROOKLYN,3.032360e+09,BROOKLYN,1005915.0,195340.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.702813,-73.921863,"(40.70281342017164, -73.92186290937498)",True

**Step 4. Group your dataframe df_graffiti to get the count of requests per community_board. Use .nlargest() to identify which Community District has the highest count.**

***The 01 Brooklyn community has the highest count of 311 requests while 64 Manhattan received the lowest number of 311 requests.***

In [11]:
graffiti_cb_count = df_graffiti.groupby('community_board').size().nlargest(400).reset_index(name='count')
graffiti_cb_count

              community_board  count
0   01 BROOKLYN                1797
1   03 MANHATTAN               1593
2   04 BROOKLYN                1429
3   03 BROOKLYN                1252
4   05 BROOKLYN                962
5   07 BROOKLYN                779
6   Unspecified BRONX          615
7   02 MANHATTAN               598
8   Unspecified BROOKLYN       591
9   01 QUEENS                  572
10  0 Unspecified              540
11  12 QUEENS                  539
12  12 BROOKLYN                532
13  14 BROOKLYN                532
14  08 BROOKLYN                505
15  17 BROOKLYN                480
16  11 BROOKLYN                474
17  09 QUEENS                  470
18  09 BRONX                   464
19  12 MANHATTAN               459
20  06 BRONX                   446
21  12 BRONX                   426
22  18 BROOKLYN                410
23  Unspecified MANHATTAN      405
24  09 BROOKLYN                403
25  05 BRONX                   402
26  06 BROOKLYN                401
27  16 BROOKLYN                371
28  04 QUEENS                  353
29  07 QUEENS                  350
30  04 BRONX                   336
31  15 BROOKLYN                329
32  07 BRONX                   322
33  03 BRONX                   320
34  02 BROOKLYN                315
35  01 BRONX                   311
36  04 MANHATTAN               306
37  05 MANHATTAN               283
38  08 MANHATTAN               273
39  10 BROOKLYN                268
40  11 BRONX                   267
41  10 MANHATTAN               266
42  01 STATEN ISLAND           255
43  Unspecified QUEENS         254
44  02 BRONX                   243
45  11 MANHATTAN               229
46  07 MANHATTAN               224
47  02 QUEENS                  219
48  05 QUEENS                  219
49  10 QUEENS                  202
50  03 QUEENS                  202
51  09 MANHATTAN               201
52  13 BROOKLYN                196
53  06 MANHATTAN               162
54  10 BRONX                   150
55  01 MANHATTAN               146
56  13 QUEENS                  142
57  08 QUEENS                  129
58  08 BRONX                   127
59  14 QUEENS                  91
60  06 QUEENS                  68
61  11 QUEENS                  57
62  02 STATEN ISLAND           42
63  03 STATEN ISLAND           40
64  Unspecified STATEN ISLAND  8
65  26 BRONX                   5
66  81 QUEENS                  5
67  27 BRONX                   4
68  28 BRONX                   2
69  55 BROOKLYN                2
70  64 MANHATTAN               1